/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'yuasano' at '16/05/04 14:20' with Gradle 2.4
 *
 * @author yuasano, @date 16/05/04 14:20
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
