/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'yuasano' at '16/05/04 14:20' with Gradle 2.4
 *
 * @author yuasano, @date 16/05/04 14:20
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
